spring:
  application:
    name: template-backend
  profiles:
    default: local
  datasource:
    url: ${TEMPLATE_DB_URL:jdbc:postgresql://localhost:5432/template}
    username: ${TEMPLATE_DB_USERNAME:template}
    password: ${TEMPLATE_DB_PASSWORD:template}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  mail:
    host: ${TEMPLATE_MAIL_HOST:localhost}
    port: ${TEMPLATE_MAIL_PORT:1025}
    username: ${TEMPLATE_MAIL_USERNAME:}
    password: ${TEMPLATE_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MILESTORY_MAIL_AUTH:false}
          starttls:
            enable: ${MILESTORY_MAIL_STARTTLS:false}

template:
  jwt:
    issuer: ${TEMPLATE_JWT_ISSUER:template-local}
    audience: ${TEMPLATE_JWT_AUDIENCE:template-web}
    access-token-ttl: ${TEMPLATE_JWT_ACCESS_TOKEN_TTL:PT15M}
    refresh-token-ttl: ${TEMPLATE_JWT_REFRESH_TOKEN_TTL:P30D}
    secret: ${TEMPLATE_JWT_SECRET:replace-me-in-real-environments}
