spring:
  application:
    name: template-backend
  profiles:
    default: local
  datasource:
    url: ${TEMPLATE_DB_URL:jdbc:postgresql://localhost:5432/template}
    username: ${TEMPLATE_DB_USERNAME:template}
    password: ${TEMPLATE_DB_PASSWORD:template}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml