spring:
  datasource:
    url: jdbc:postgresql://${TEMPLATE_DB_HOST:localhost}:${TEMPLATE_DB_PORT:5432}/${TEMPLATE_DB_NAME:template}
    username: ${TEMPLATE_DB_USERNAME:template}
    password: ${TEMPLATE_DB_PASSWORD:template}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml